version: "3.7"
networks:
    dic_net:
      driver: bridge
secrets:
    MYSQL_ROOT_PASSWORD:
        file: ./secrets/MYSQL_ROOT_PASSWORD.txt
    MYSQL_PASSWORD:
        file: ./secrets/MYSQL_PASSWORD.txt
services:
    mysql:
        container_name: dic-mysql
        image: mysql:latest
        command: --default-authentication-plugin=mysql_native_password
        restart: unless-stopped
        secrets:
            - MYSQL_ROOT_PASSWORD
            - MYSQL_PASSWORD
        environment:
            MYSQL_ROOT_PASSWORD_FILE: /run/secrets/MYSQL_ROOT_PASSWORD
            MYSQL_PASSWORD_FILE: /run/secrets/MYSQL_PASSWORD
            MYSQL_DATABASE: dic
            MYSQL_USER: dic
        volumes: 
            - ./dbdata:/var/lib/mysql
        networks:
            - dic_net
    adminer:
        image: adminer
        restart: unless-stopped
        ports:
            - 8080:8080
        environment: 
            ADMINER_DEFAULT_SERVER: mysql
            ADMINER_DESIGN: 'konya'
        networks:
            - dic_net
    app:
        build:
            context: backend
        container_name: backend-service
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - ./backend/:/var/www
            - ./backend/docker-configs/php.ini:/usr/local/etc/php/conf.d/local.ini
            - ./oauth-keys:/var/www/storage/oauth-keys
        networks:
            - dic_net
        ports:
            - 8000:80
        depends_on: 
            - mysql